.TH HTTP-MUSIC-CRAWL-YOUTUBE 1

.SH NAME
http-music-crawl-youtube - create a playlist file from a YouTube playlist URL

.SH SYNOPSIS
.B http-music crawl-youtube
<youtube playlist URL>

.SH DESCRIPTION
\fBhttp-music-crawl-youtube\fR is a simple utility that creates a playlist file from a YouTube playlist, given its URL.
It requires the \fByoutube-dl\fR command line utility to download tracks.
(It's also necessary to have youtube-dl to play them.)
.PP
crawl-youtube is not idiot proof.
It will not work with private playlists.
